### ISSUE TITLE
Why not using structs?

### ISSUE THREAD

**Issue by winxalex** [soenneker/soenneker.reflection.cache#1]
Using structs instead of classes(heap/steack) for cache X-Infos, seem logical choice to me. Maybe I'm missing something. Cache items are data containers of (infos) not expecting crazy methods on them or subclassing...Anyway great job.

**Comment by soenneker** [comment]
Hi there, thanks for your interest in the library.

Classes were chosen for several reasons. The main reason is I'm rely on lazily loading/storing all of the downstream calls that tend to happen when traversing with Reflection. It wouldn't be smart to build the entire 'tree' of a member before storing in the dictionary. That makes the initial call as fast as possible. 

Remember that only 'copies' of structs are stored and retrieved from a dictionary.

For example: let's say you get the methods on a class, and then the parameters from that method. If I was using structs, I'd have to load the method. then I'd need to store all of the parameters. Then I'd store in the dictionary. Or I'd need to replace the copy in the dictionary every time something would change. I did some benchmarking and it doesn't seem to be faster.

All of that being said, I wouldn't be surprised at all if there's a better and more clever way of doing this. I'm totally open to changes/PRs.

Please star if you like it!
